---
- name: "Get Junos OS configuration"
  hosts: juniper_switches
  connection: local
  gather_facts: no

  tasks:
    - name: "Save configuration to a file"
      juniper.device.config:
        retrieve: "committed"
        dest_dir: "/mnt/c/Users/divic/iac/"
